language: ruby
bundler_args: --without development

rvm:
  - 2.0.0
  - 2.2.2
  - jruby-19mode

env:
  - PATTERN=log_service
  - PATTERN=synchrony

before_install:
  - gem update bundler
  - bundle --version
  - gem update --system 2.1.11
  - gem --version

matrix:
  exclude:
    - rvm: jruby-19mode
      env: PATTERN=synchrony

script:
  - bundle exec rake pattern
